name: PR lint

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ github.token }}
        sync-labels: true
